package com.malen.hypatia.helidon;

import com.malen.hypatia.helidon.service.GreetService;
import io.helidon.common.config.Config;
import io.helidon.logging.common.LogConfig;
import io.helidon.service.registry.Services;
import io.helidon.webserver.WebServer;
import io.helidon.webserver.http.HttpRouting;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


public class Demo {
    private static final Logger log = LoggerFactory.getLogger(Demo.class);

    public static void main(String[] args) {
        LogConfig.configureRuntime();
        // many examples, including the demo generated by helidon, use deprecated method [io.helidon.config.Config#global(io.helidon.config.Config)]
        Services.set(Config.class, Config.create());

        WebServer server = WebServer.builder()
                .config(Services.get(Config.class).get("server"))
                .routing(Demo::route)
                .build()
                .start();

        log.info("Server started on port {}", server.port());
    }

    private static void route(HttpRouting.Builder builder) {
        builder.register("/greeting", new GreetService());
    }
}
